export const FETCH_INPUT_CHANGE = 'FETCH_INPUT_CHANGE';

export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const FETCH_WEB_START = 'FETCH_WEB_START';
export const FETCH_WEB_SUCCESS = 'FETCH_WEB_SUCCESS';
export const FETCH_WEB_FAIL = 'FETCH_WEB_FAIL';

export const FETCH_CHALLENGE_START = 'FETCH_CHALLENGE_START';
export const FETCH_CHALLENGE_SUCCESS = 'FETCH_CHALLENGE_SUCCESS';
export const FETCH_CHALLENGE_FAIL = 'FETCH_CHALLENGE_FAIL';

export const FETCH_CLASS_MEMBERSHIP_START = 'FETCH_CLASS_MEMBERSHIP_START';
export const FETCH_CLASS_MEMBERSHIP_SUCCESS = 'FETCH_CLASS_MEMBERSHIP_SUCCESS';
export const FETCH_CLASS_MEMBERSHIP_FAIL = 'FETCH_CLASS_MEMBERSHIP_FAIL';

export const FETCH_UNFINISHED_VIDEOS_START = 'FETCH_UNFINISHED_VIDEOS_START';
export const FETCH_UNFINISHED_VIDEOS_SUCCESS =
  'FETCH_UNFINISHED_VIDEOS_SUCCESS';
export const FETCH_UNFINISHED_VIDEOS_FAIL = 'FETCH_UNFINISHED_VIDEOS_FAIL';

export const FETCH_FAVOURITE_VIDEOS_START = 'FETCH_FAVOURITE_VIDEOS_START';
export const FETCH_FAVOURITE_VIDEOS_SUCCESS = 'FETCH_FAVOURITE_VIDEOS_SUCCESS';
export const FETCH_FAVOURITE_VIDEOS_FAIL = 'FETCH_FAVOURITE_VIDEOS_FAIL';

export const FETCH_TOPTEN_VIDEOS_START = 'FETCH_TOPTEN_VIDEOS_START';
export const FETCH_TOPTEN_VIDEOS_SUCCESS = 'FETCH_TOPTEN_VIDEOS_SUCCESS';
export const FETCH_TOPTEN_VIDEOS_FAIL = 'FETCH_TOPTEN_VIDEOS_FAIL';

export const FETCH_RECENT_ACTIVITY_START = 'FETCH_RECENT_ACTIVITY_START';
export const FETCH_RECENT_ACTIVITY_SUCCESS = 'FETCH_RECENT_ACTIVITY_SUCCESS';
export const FETCH_RECENT_ACTIVITY_FAIL = 'FETCH_RECENT_ACTIVITY_FAIL';

export const FETCH_SUBJECT_RELATED_LESSONS_START =
  'FETCH_SUBJECT_RELATED_LESSONS_START';
export const FETCH_SUBJECT_RELATED_LESSONS_SUCCESS =
  'FETCH_SUBJECT_RELATED_LESSONS_SUCCESS';
export const FETCH_SUBJECT_RELATED_LESSONS_FAIL =
  'FETCH_SUBJECT_RELATED_LESSONS_FAIL';

export const FETCH_PASTQUESTION_SUBJECT_START =
  'FETCH_PASTQUESTION_SUBJECT_START';
export const FETCH_PASTQUESTION_SUBJECT_SUCCESS =
  'FETCH_PASTQUESTION_SUBJECT_SUCCESS';
export const FETCH_PASTQUESTION_SUBJECT_FAIL =
  'FETCH_PASTQUESTION_SUBJECT_FAIL';

export const FETCH_PASTQUESTION_START = 'FETCH_PASTQUESTION_START';
export const FETCH_PASTQUESTION_SUCCESS = 'FETCH_PASTQUESTION_SUCCESS';
export const FETCH_PASTQUESTION_FAIL = 'FETCH_PASTQUESTION_FAIL';
